// Resonance - Intelligence Sources Data
// Job boards with salary ranges, difficulty levels, and detailed metadata

const jobBoards = [
    {
        id: 1,
        name: "We Work Remotely",
        url: "https://weworkremotely.com/",
        region: "Global",
        focus: "Remote-first tech + product roles",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 60000,
        salaryMax: 180000,
        bestForRoles: "Full Stack, Backend, Product, AI-adjacent roles",
        status: "active"
    },
    {
        id: 2,
        name: "Remote OK",
        url: "https://remoteok.com/",
        region: "Global",
        focus: "Remote tech + startup roles",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 60000,
        salaryMax: 180000,
        bestForRoles: "Backend, DevOps, AI/LLM integration, Full Stack",
        status: "active"
    },
    {
        id: 3,
        name: "FlexJobs",
        url: "https://www.flexjobs.com/",
        region: "Global",
        focus: "Curated remote & flexible work (paid access)",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 200000,
        bestForRoles: "Senior remote professionals; broad tech roles",
        status: "active",
        notes: "Paid membership; tends to reduce low-quality listings."
    },
    {
        id: 4,
        name: "Wellfound (AngelList)",
        url: "https://wellfound.com/jobs",
        region: "Global",
        focus: "Startup jobs (tech/product)",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 60000,
        salaryMax: 180000,
        bestForRoles: "Startup Full Stack, AI engineer, early-team roles",
        status: "active"
    },
    {
        id: 5,
        name: "LinkedIn Jobs",
        url: "https://www.linkedin.com/jobs/",
        region: "Global",
        focus: "All industries (strong tech coverage)",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 60000,
        salaryMax: 200000,
        bestForRoles: "Senior Eng, Lead, Full Stack, AI/ML",
        status: "active"
    },
    {
        id: 6,
        name: "Remote.co",
        url: "https://remote.co/remote-jobs/",
        region: "Global",
        focus: "Remote-first roles + resources",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 160000,
        bestForRoles: "Remote engineering + ops roles",
        status: "active"
    },
    {
        id: 7,
        name: "Working Nomads",
        url: "https://www.workingnomads.com/jobs",
        region: "Global",
        focus: "Curated remote listings",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 160000,
        bestForRoles: "Remote developers, PMs, DevOps",
        status: "active"
    },
    {
        id: 8,
        name: "Remotive",
        url: "https://remotive.com/remote-jobs",
        region: "Global",
        focus: "Remote tech & startup roles",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 160000,
        bestForRoles: "Full Stack, Backend, some AI roles",
        status: "active"
    },
    {
        id: 9,
        name: "Jobspresso",
        url: "https://jobspresso.co/",
        region: "Global",
        focus: "Curated remote jobs (tech-heavy)",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 150000,
        bestForRoles: "Engineering, product",
        status: "active"
    },
    {
        id: 10,
        name: "Remote100K",
        url: "https://remote100k.com/",
        region: "Global",
        focus: "High-paying remote roles",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 100000,
        salaryMax: 250000,
        bestForRoles: "Senior Eng, Staff/Lead, AI-adjacent",
        status: "active"
    },
    {
        id: 11,
        name: "Arc",
        url: "https://arc.dev/remote-jobs",
        region: "Global",
        focus: "Developer matching + remote jobs",
        remote: true,
        freelance: true,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Full Stack, Frontend, Backend",
        status: "active"
    },
    {
        id: 12,
        name: "Upwork",
        url: "https://www.upwork.com/",
        region: "Global",
        focus: "Freelance marketplace",
        remote: true,
        freelance: true,
        difficulty: 4,
        salaryMin: 30000,
        salaryMax: 200000,
        bestForRoles: "Freelance Full Stack, AI prototypes, integrations",
        status: "active"
    },
    {
        id: 13,
        name: "Toptal",
        url: "https://www.toptal.com/",
        region: "Global",
        focus: "Vetted elite freelance network",
        remote: true,
        freelance: true,
        difficulty: 5,
        salaryMin: 100000,
        salaryMax: 250000,
        bestForRoles: "Senior engineers, AI specialists",
        status: "active"
    },
    {
        id: 14,
        name: "Outsourcely",
        url: "https://www.outsourcely.com/",
        region: "Global",
        focus: "Remote full-time + contract opportunities",
        remote: true,
        freelance: true,
        difficulty: 3,
        salaryMin: 40000,
        salaryMax: 140000,
        bestForRoles: "Remote Full Stack",
        status: "active"
    },
    {
        id: 15,
        name: "Indeed",
        url: "https://www.indeed.com/",
        region: "Global",
        focus: "Aggregated listings",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 40000,
        salaryMax: 180000,
        bestForRoles: "Broad tech jobs",
        status: "active"
    },
    {
        id: 16,
        name: "ZipRecruiter",
        url: "https://www.ziprecruiter.com/",
        region: "US/Global",
        focus: "Aggregated roles + matching",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 50000,
        salaryMax: 180000,
        bestForRoles: "Full Stack, DevOps",
        status: "active"
    },
    {
        id: 17,
        name: "Dice",
        url: "https://www.dice.com/",
        region: "US (some Global)",
        focus: "Tech & IT jobs",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Backend, Cloud, DevOps",
        status: "active"
    },
    {
        id: 18,
        name: "SimplyHired",
        url: "https://www.simplyhired.com/",
        region: "Global",
        focus: "Aggregated listings",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 40000,
        salaryMax: 180000,
        bestForRoles: "General tech roles",
        status: "active"
    },
    {
        id: 19,
        name: "Jooble",
        url: "https://jooble.org/",
        region: "Global",
        focus: "Aggregated listings",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 40000,
        salaryMax: 180000,
        bestForRoles: "General tech roles",
        status: "active"
    },
    {
        id: 20,
        name: "Himalayas",
        url: "https://himalayas.app/jobs",
        region: "Global",
        focus: "Remote-first job board (tech-heavy)",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 180000,
        bestForRoles: "Remote engineers, startups",
        status: "active"
    },
    {
        id: 21,
        name: "JustRemote",
        url: "https://justremote.co/",
        region: "Global",
        focus: "Remote jobs aggregator",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 45000,
        salaryMax: 170000,
        bestForRoles: "Remote software roles",
        status: "active"
    },
    {
        id: 22,
        name: "EU Remote Jobs",
        url: "https://euremotejobs.com/",
        region: "Europe",
        focus: "EU-friendly remote constraints",
        remote: true,
        freelance: false,
        difficulty: 3,
        bestForRoles: "EU-based remote engineers",
        status: "active"
    },
    {
        id: 23,
        name: "Built In (Remote)",
        url: "https://builtin.com/jobs/remote",
        region: "US (mostly)",
        focus: "Tech companies + startup-ish roles",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 200000,
        bestForRoles: "Software engineers, data/AI roles",
        status: "active"
    },
    {
        id: 24,
        name: "Otta",
        url: "https://otta.com/",
        region: "UK/US (expanding)",
        focus: "Curated tech roles with matching",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 60000,
        salaryMax: 200000,
        bestForRoles: "Product engineers, startup roles",
        status: "active"
    },
    {
        id: 25,
        name: "Y Combinator Jobs",
        url: "https://www.ycombinator.com/jobs",
        region: "Global",
        focus: "YC startup roles",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 70000,
        salaryMax: 220000,
        bestForRoles: "Startup Full Stack, Backend, AI engineering",
        status: "active"
    },
    {
        id: 26,
        name: "Hacker News — Who is hiring?",
        url: "https://news.ycombinator.com/submitted?id=whoishiring",
        region: "Global",
        focus: "Monthly hiring threads",
        remote: true,
        freelance: false,
        difficulty: 4,
        bestForRoles: "Senior engineers; direct outreach",
        status: "active",
        notes: "Not a classic job board; recurring thread."
    },
    {
        id: 27,
        name: "ai-jobs.net",
        url: "https://ai-jobs.net/",
        region: "Global",
        focus: "AI/ML job board",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 80000,
        salaryMax: 250000,
        bestForRoles: "AI/ML, LLM engineering, applied ML",
        status: "active"
    },
    {
        id: 28,
        name: "Hugging Face Jobs",
        url: "https://huggingface.co/jobs",
        region: "Global",
        focus: "AI ecosystem roles",
        remote: true,
        freelance: false,
        difficulty: 4,
        bestForRoles: "LLM ecosystem, ML tooling, applied AI",
        status: "active"
    },
    {
        id: 29,
        name: "Stack Overflow Jobs",
        url: "https://stackoverflow.com/jobs",
        region: "Global",
        focus: "Developer jobs (historical)",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Software engineering",
        status: "inactive",
        notes: "Discontinued; kept for historical completeness."
    },
    {
        id: 30,
        name: "Weights & Biases Careers",
        url: "https://wandb.ai/careers",
        region: "Global",
        focus: "MLOps & AI infra",
        remote: true,
        freelance: false,
        difficulty: 4,
        bestForRoles: "ML Engineers, DevOps",
        status: "active"
    },
    {
        id: 31,
        name: "LangChain Jobs",
        url: "https://discord.gg/langchain",
        region: "Global",
        focus: "LLM App Dev",
        remote: true,
        freelance: false,
        difficulty: 4,
        bestForRoles: "LangChain/LLM App Engineers",
        status: "active",
        notes: "Community Board (Discord)"
    },
    {
        id: 32,
        name: "Replicate Jobs",
        url: "https://replicate.com/careers",
        region: "Global",
        focus: "AI Infra & Apps",
        remote: true,
        freelance: false,
        difficulty: 4,
        bestForRoles: "Backend + AI Integration Eng",
        status: "active"
    },
    {
        id: 33,
        name: "OpenRouter Careers",
        url: "https://openrouter.ai/careers",
        region: "Global",
        focus: "AI API & Routing",
        remote: true,
        freelance: false,
        difficulty: 4,
        bestForRoles: "Full Stack + AI API Engineers",
        status: "active"
    },
    {
        id: 34,
        name: "O'Reilly AI Job Board",
        url: "https://www.oreilly.com/ai/job-board/",
        region: "Global",
        focus: "Enterprise AI",
        remote: true,
        freelance: false,
        difficulty: 4,
        bestForRoles: "Applied AI, Data Science",
        status: "active"
    },
    {
        id: 35,
        name: "Remote Leaf",
        url: "https://remoteleaf.com",
        region: "APAC Focus",
        focus: "Aggregator + alerts",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 170000,
        bestForRoles: "APAC Remote Engineers",
        status: "active",
        notes: "APAC friendly"
    },
    {
        id: 36,
        name: "AI Jobs Board",
        url: "https://aijobsboard.net/",
        region: "Global",
        focus: "AI/ML roles globally",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 80000,
        salaryMax: 220000,
        bestForRoles: "AI/ML Engineers",
        status: "active"
    },
    {
        id: 37,
        name: "Kaggle Jobs",
        url: "https://www.kaggle.com/jobs",
        region: "Global",
        focus: "Data science & ML",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 70000,
        salaryMax: 200000,
        bestForRoles: "Data Scientists, ML Engineers",
        status: "active"
    },
    {
        id: 38,
        name: "DataJobs",
        url: "https://datajobs.com/",
        region: "US (mostly)",
        focus: "Data eng, ML, analytics",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Data Engineers, Analysts",
        status: "active"
    },
    {
        id: 39,
        name: "AI/ML Jobs",
        url: "https://www.aiml.jobs/",
        region: "Global",
        focus: "Pure AI/ML curation",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 90000,
        salaryMax: 250000,
        bestForRoles: "AI Researchers, ML Engineers",
        status: "active"
    },
    {
        id: 40,
        name: "Deep Learning Jobs",
        url: "https://deeplearningjobs.io/",
        region: "Global",
        focus: "Deep learning focus",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 100000,
        salaryMax: 250000,
        bestForRoles: "Deep Learning Researchers",
        status: "active"
    },
    {
        id: 41,
        name: "NLP Job Board",
        url: "https://nlpjob.com/",
        region: "Global",
        focus: "NLP/LLM specific",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 90000,
        salaryMax: 230000,
        bestForRoles: "NLP Engineers",
        status: "active"
    },
    {
        id: 42,
        name: "MLconf Jobs",
        url: "https://mlconf.com/jobs/",
        region: "Global",
        focus: "ML conference community",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 80000,
        salaryMax: 200000,
        bestForRoles: "ML Practitioners",
        status: "active"
    },
    {
        id: 43,
        name: "OpenAI Careers",
        url: "https://openai.com/careers",
        region: "Global",
        focus: "OpenAI direct",
        remote: true,
        freelance: false,
        difficulty: 5,
        salaryMin: 150000,
        salaryMax: 400000,
        bestForRoles: "Research Scientists, AI Engineers",
        status: "active"
    },
    {
        id: 44,
        name: "Anthropic Careers",
        url: "https://www.anthropic.com/careers",
        region: "Global",
        focus: "Anthropic direct",
        remote: true,
        freelance: false,
        difficulty: 5,
        salaryMin: 150000,
        salaryMax: 400000,
        bestForRoles: "AI Safety Researchers, Engineers",
        status: "active"
    },
    {
        id: 45,
        name: "DeepMind Careers",
        url: "https://deepmind.google/careers/",
        region: "Global",
        focus: "DeepMind/Google",
        remote: true,
        freelance: false,
        difficulty: 5,
        salaryMin: 150000,
        salaryMax: 400000,
        bestForRoles: "Research Scientists",
        status: "active"
    },
    {
        id: 46,
        name: "Cohere Jobs",
        url: "https://cohere.com/careers",
        region: "Global",
        focus: "LLM company",
        remote: true,
        freelance: false,
        difficulty: 5,
        salaryMin: 120000,
        salaryMax: 300000,
        bestForRoles: "LLM Engineers",
        status: "active"
    },
    {
        id: 47,
        name: "Stability AI Jobs",
        url: "https://stability.ai/careers",
        region: "Global",
        focus: "Generative AI",
        remote: true,
        freelance: false,
        difficulty: 5,
        salaryMin: 100000,
        salaryMax: 280000,
        bestForRoles: "GenAI Engineers",
        status: "active"
    },
    {
        id: 48,
        name: "NoDesk",
        url: "https://nodesk.co/remote-jobs/",
        region: "Global",
        focus: "Strictly remote",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 60000,
        salaryMax: 170000,
        bestForRoles: "Digital Nomads",
        status: "active"
    },
    {
        id: 49,
        name: "Pangian",
        url: "https://pangian.com/job-travel-remote/",
        region: "Global",
        focus: "Remote + travel/visa",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 160000,
        bestForRoles: "Nomads",
        status: "active"
    },
    {
        id: 50,
        name: "Dynamite Jobs",
        url: "https://dynamitejobs.com/",
        region: "Global",
        focus: "Vetted remote",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Remote Professionals",
        status: "active"
    },
    {
        id: 51,
        name: "Remote Hub",
        url: "https://remotehub.com/remote-jobs",
        region: "Global",
        focus: "Remote + company reviews",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 55000,
        salaryMax: 160000,
        bestForRoles: "Remote Workers",
        status: "active"
    },
    {
        id: 52,
        name: "Lemon.io",
        url: "https://lemon.io/",
        region: "Global",
        focus: "Vetted devs for startups",
        remote: true,
        freelance: true,
        difficulty: 4,
        salaryMin: 60000,
        salaryMax: 150000,
        bestForRoles: "Freelance Developers",
        status: "active"
    },
    {
        id: 53,
        name: "X-Team",
        url: "https://x-team.com/join/",
        region: "Global",
        focus: "Remote dev community",
        remote: true,
        freelance: true,
        difficulty: 4,
        salaryMin: 80000,
        salaryMax: 180000,
        bestForRoles: "Senior Developers",
        status: "active"
    },
    {
        id: 54,
        name: "Remote Year Jobs",
        url: "https://www.remoteyear.com/jobs",
        region: "Global",
        focus: "Nomad programs",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 140000,
        bestForRoles: "Travelers",
        status: "active"
    },
    {
        id: 55,
        name: "Crossover",
        url: "https://www.crossover.com/jobs",
        region: "Global",
        focus: "Long-term remote",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 60000,
        salaryMax: 200000,
        bestForRoles: "Senior Talent",
        status: "active"
    },
    {
        id: 56,
        name: "Contra",
        url: "https://contra.com/",
        region: "Global",
        focus: "Freelance/independent",
        remote: true,
        freelance: true,
        difficulty: 3,
        salaryMin: 40000,
        salaryMax: 180000,
        bestForRoles: "Independents",
        status: "active"
    },
    {
        id: 57,
        name: "EuroTechJobs",
        url: "https://www.eurotechjobs.com/",
        region: "Europe",
        focus: "EU tech roles",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 130000,
        bestForRoles: "EU Tech",
        status: "active"
    },
    {
        id: 58,
        name: "SwissDevJobs",
        url: "https://swissdevjobs.ch/",
        region: "Switzerland",
        focus: "Switzerland dev roles",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 90000,
        salaryMax: 180000,
        bestForRoles: "Swiss Devs",
        status: "active"
    },
    {
        id: 59,
        name: "Landing.Jobs",
        url: "https://landing.jobs/",
        region: "Europe",
        focus: "Portugal/EU startups",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 40000,
        salaryMax: 100000,
        bestForRoles: "EU Startups",
        status: "active"
    },
    {
        id: 60,
        name: "German Tech Jobs",
        url: "https://germantechjobs.de/",
        region: "Germany",
        focus: "Germany tech",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 55000,
        salaryMax: 120000,
        bestForRoles: "German Devs",
        status: "active"
    },
    {
        id: 61,
        name: "Relocate.me",
        url: "https://relocate.me/",
        region: "Global",
        focus: "Visa/relocation jobs",
        remote: false,
        freelance: false,
        difficulty: 3,
        salaryMin: 50000,
        salaryMax: 140000,
        bestForRoles: "Relocators",
        status: "active"
    },
    {
        id: 62,
        name: "techjobsforgood",
        url: "https://techjobsforgood.com/",
        region: "Global",
        focus: "Impact tech (EU/US)",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 60000,
        salaryMax: 150000,
        bestForRoles: "Mission-driven",
        status: "active"
    },
    {
        id: 63,
        name: "cord",
        url: "https://cord.co/",
        region: "UK/EU",
        focus: "UK/EU startup tech",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 60000,
        salaryMax: 150000,
        bestForRoles: "Startup Talent",
        status: "active"
    },
    {
        id: 64,
        name: "Hackajob",
        url: "https://hackajob.com/",
        region: "UK/EU",
        focus: "UK/EU tech matching",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 55000,
        salaryMax: 140000,
        bestForRoles: "Matched Engineers",
        status: "active"
    },
    {
        id: 65,
        name: "talent.io",
        url: "https://www.talent.io/",
        region: "Europe",
        focus: "EU vetted engineers",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 50000,
        salaryMax: 130000,
        bestForRoles: "Vetted Engineers",
        status: "active"
    },
    {
        id: 66,
        name: "Hired",
        url: "https://hired.com/",
        region: "US/UK",
        focus: "US/UK tech matching",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 80000,
        salaryMax: 200000,
        bestForRoles: "Tech Talent",
        status: "active"
    },
    {
        id: 67,
        name: "Triplebyte",
        url: "https://triplebyte.com/",
        region: "US",
        focus: "Vetted eng matching",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 100000,
        salaryMax: 220000,
        bestForRoles: "Vetted Engineers",
        status: "active"
    },
    {
        id: 68,
        name: "Levels.fyi Jobs",
        url: "https://www.levels.fyi/jobs/",
        region: "US/Global",
        focus: "Comp-transparent roles",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 80000,
        salaryMax: 400000,
        bestForRoles: "High Earners",
        status: "active"
    },
    {
        id: 69,
        name: "Key Values",
        url: "https://www.keyvalues.com/",
        region: "US/Global",
        focus: "Culture-first matching",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 80000,
        salaryMax: 180000,
        bestForRoles: "Culture Fit",
        status: "active"
    },
    {
        id: 70,
        name: "Underdog.io",
        url: "https://underdog.io/",
        region: "US",
        focus: "Startup talent",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 90000,
        salaryMax: 200000,
        bestForRoles: "Startup Talent",
        status: "active"
    },
    {
        id: 71,
        name: "Vettery",
        url: "https://www.vettery.com/",
        region: "US/Global",
        focus: "Employer marketplace",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Active Seekers",
        status: "active"
    },
    {
        id: 72,
        name: "A.Team",
        url: "https://www.a.team/",
        region: "Global",
        focus: "Elite product teams",
        remote: true,
        freelance: true,
        difficulty: 5,
        salaryMin: 150000,
        salaryMax: 300000,
        bestForRoles: "Product Teams",
        status: "active"
    },
    {
        id: 73,
        name: "Braintrust",
        url: "https://www.usebraintrust.com/",
        region: "Global",
        focus: "Web3/decentralized talent",
        remote: true,
        freelance: true,
        difficulty: 4,
        salaryMin: 80000,
        salaryMax: 250000,
        bestForRoles: "Web3 Devs",
        status: "active"
    },
    {
        id: 74,
        name: "GitHub Jobs",
        url: "https://jobs.github.com/",
        region: "Global",
        focus: "Developer roles (Historical)",
        remote: true,
        freelance: false,
        difficulty: 2,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Developers",
        status: "inactive",
        notes: "Historical reference"
    },
    {
        id: 75,
        name: "Authentic Jobs",
        url: "https://authenticjobs.com/",
        region: "Global",
        focus: "Design + dev",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 60000,
        salaryMax: 160000,
        bestForRoles: "Designers, Devs",
        status: "active"
    },
    {
        id: 76,
        name: "Smashing Jobs",
        url: "https://jobs.smashingmagazine.com/",
        region: "Global",
        focus: "Frontend/design",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 60000,
        salaryMax: 150000,
        bestForRoles: "Frontend Devs",
        status: "active"
    },
    {
        id: 77,
        name: "JSJobbs",
        url: "https://jsjobbs.com/",
        region: "Global",
        focus: "JavaScript focused",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "JS/TS Devs",
        status: "active"
    },
    {
        id: 78,
        name: "RubyNow",
        url: "https://jobs.rubynow.com/",
        region: "Global",
        focus: "Ruby/Rails jobs",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 80000,
        salaryMax: 180000,
        bestForRoles: "Ruby Devs",
        status: "active"
    },
    {
        id: 79,
        name: "Golang Cafe",
        url: "https://golang.cafe/",
        region: "Global",
        focus: "Go developers",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 80000,
        salaryMax: 200000,
        bestForRoles: "Go Devs",
        status: "active"
    },
    {
        id: 80,
        name: "Rust Jobs",
        url: "https://rustjobs.dev/",
        region: "Global",
        focus: "Rust developers",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 90000,
        salaryMax: 220000,
        bestForRoles: "Rust Devs",
        status: "active"
    },
    {
        id: 81,
        name: "Python.org Jobs",
        url: "https://www.python.org/jobs/",
        region: "Global",
        focus: "Python roles",
        remote: true,
        freelance: false,
        difficulty: 3,
        salaryMin: 70000,
        salaryMax: 180000,
        bestForRoles: "Python Devs",
        status: "active"
    },
    {
        id: 82,
        name: "r/forhire",
        url: "https://www.reddit.com/r/forhire/",
        region: "Global",
        focus: "Reddit freelance",
        remote: true,
        freelance: true,
        difficulty: 2,
        bestForRoles: "Freelancers",
        status: "active"
    },
    {
        id: 83,
        name: "Sequoia Jobs",
        url: "https://www.sequoiacap.com/jobs/",
        region: "Global",
        focus: "Sequoia portfolio",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 100000,
        salaryMax: 250000,
        bestForRoles: "Startup Talent",
        status: "active"
    },
    {
        id: 84,
        name: "a16z Jobs",
        url: "https://a16z.com/portfolio-jobs/",
        region: "Global",
        focus: "a16z portfolio",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 100000,
        salaryMax: 280000,
        bestForRoles: "VC Startup Talent",
        status: "active"
    },
    {
        id: 85,
        name: "FirstRound Jobs",
        url: "https://firstround.com/talent/",
        region: "Global",
        focus: "First Round portfolio",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 90000,
        salaryMax: 220000,
        bestForRoles: "Early Stage Talent",
        status: "active"
    },
    {
        id: 86,
        name: "BreakoutList",
        url: "https://breakoutlist.com/",
        region: "Global",
        focus: "Fast-growing startups",
        remote: true,
        freelance: false,
        difficulty: 4,
        salaryMin: 80000,
        salaryMax: 200000,
        bestForRoles: "Growth Stage Talent",
        status: "active"
    }
];

// Export for Chrome extension
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { jobBoards };
}
